name: Qt UI Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils qt5-default qttools5-dev-tools

      - name: Check syntax of mainwindow.ui xmllint
        run: |
            xmllint --noout mainwindow.ui
            
      - name: Check syntax of mainwindow.ui uic
        run: |
            uic mainwindow.ui -o /dev/null

